### ISSUE TITLE
Version generator fails for version with 4 parts, e.g. 2.0.11.2

### ISSUE THREAD

**Issue by jasinner** [jasinner/victims-db-builder#4]
Try: "python -m unittest test_vulnerability"

It should fail with:

======================================================================
ERROR: test_print_flaw (test_vulnerability.TestVulnerability)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_vulnerability.py", line 8, in test_print_flaw
    vul = vulnerability.Vulnerability('test/6504.yaml')
  File "vulnerability.py", line 59, in __init__
    self.add_libraries(data['affected'])
  File "vulnerability.py", line 71, in add_libraries
    version, groupId, artifactId))
  File "library.py", line 92, in __init__
    self.confirmVersions()
  File "library.py", line 115, in confirmVersions
    firstY = float(valList[0])
ValueError: invalid literal for float(): 2.0.11

**Comment by jasinner** [comment]
Skipped the library for now, but need to come back and address this.

**Comment by jasinner** [comment]
4 digit version numbers are not maven standard version. For 4 digits, Maven does a string comparison:

For example, Maven arranges the version list in the following manner:
1.0.1.0
1.0.10.1
1.0.10.2
1.0.9.3
Version 1.0.9.3 should come before 1.0.10.1 and 1.0.10.2, but the unexpected fourth field (.3) forced Maven to evaluate the version as a string.
